# Word Embeddings

## Entrenar un Word2Vec propio

In [15]:
import time
import gensim.downloader as api
from gensim.models import Word2Vec

sentences = list(api.load("text8"))

t = time.time()
w2v = Word2Vec(sentences, vector_size=100, window=5, min_count=5,
               sg=1, negative=5, epochs=3, workers=4)
print(f"entrenado en {time.time() - t:.0f}s | vocabulario: {len(w2v.wv)}")
w2v.wv.most_similar("king", topn=5)

entrenado en 185s | vocabulario: 71290


[('prince', 0.7893252372741699),
 ('kings', 0.7303068041801453),
 ('queen', 0.724629819393158),
 ('valdemar', 0.7234973311424255),
 ('vii', 0.7124313712120056)]

In [16]:
w2v.wv.most_similar(positive=["king", "woman"], negative=["man"], topn=5)

[('prince', 0.6680655479431152),
 ('son', 0.6562895178794861),
 ('throne', 0.6532759070396423),
 ('daughter', 0.6489620208740234),
 ('empress', 0.6478549242019653)]

In [28]:
coseno(w2v.wv["banana"], w2v.wv["king"])

np.float32(0.14978597)

## Embeddings pre-entrenados (inglés) y analogías

In [23]:
glove = api.load("glove-wiki-gigaword-100")   # GloVe, embeddings de 100 dimensiones
print(glove.most_similar("king", topn=5))
print("king-queen :", round(glove.similarity("king", "queen"), 3))
print("king-banana:", round(glove.similarity("king", "banana"), 3))

[('prince', 0.7682328820228577), ('queen', 0.7507690787315369), ('son', 0.7020888328552246), ('brother', 0.6985775232315063), ('monarch', 0.6977890729904175)]
king-queen : 0.751
king-banana: 0.161


In [27]:
w2v.wv["king"]

array([-0.23269008,  0.15233599,  0.68357784,  0.29462686,  0.45992255,
       -0.12969577,  0.37649468,  0.67552483,  0.11309069,  0.41720992,
       -0.17449589, -0.12316791, -0.05822387,  1.1465619 ,  0.09893145,
       -0.14590861,  0.32964647, -0.07745606,  0.2234863 , -0.6203187 ,
        0.02555277,  0.26541266, -0.10871089, -0.45910773, -0.15183167,
        0.01298978,  0.25587538,  0.59375614, -0.5457239 ,  0.44418448,
        0.44565296,  0.04140662, -0.37642977, -0.29955536,  0.5340188 ,
        0.31065318,  0.16401678, -0.38117626,  0.14734249,  0.14195837,
        0.44222933, -0.14769039, -0.57583505, -0.05883519,  0.11770912,
       -0.00611962, -0.22428584,  0.24106176,  0.24602732,  0.14263156,
        0.21005803, -0.15398636, -0.277525  , -0.06137187,  0.00536182,
       -0.06490895, -0.08401243,  0.2410443 ,  0.07266694, -0.5078228 ,
        0.21813102,  0.19102784,  0.05718689, -0.24209309, -0.4069015 ,
        0.17861743, -0.05162075,  0.544123  , -0.35205016,  0.55

In [25]:
glove["king"]

array([-0.32307 , -0.87616 ,  0.21977 ,  0.25268 ,  0.22976 ,  0.7388  ,
       -0.37954 , -0.35307 , -0.84369 , -1.1113  , -0.30266 ,  0.33178 ,
       -0.25113 ,  0.30448 , -0.077491, -0.89815 ,  0.092496, -1.1407  ,
       -0.58324 ,  0.66869 , -0.23122 , -0.95855 ,  0.28262 , -0.078848,
        0.75315 ,  0.26584 ,  0.3422  , -0.33949 ,  0.95608 ,  0.065641,
        0.45747 ,  0.39835 ,  0.57965 ,  0.39267 , -0.21851 ,  0.58795 ,
       -0.55999 ,  0.63368 , -0.043983, -0.68731 , -0.37841 ,  0.38026 ,
        0.61641 , -0.88269 , -0.12346 , -0.37928 , -0.38318 ,  0.23868 ,
        0.6685  , -0.43321 , -0.11065 ,  0.081723,  1.1569  ,  0.78958 ,
       -0.21223 , -2.3211  , -0.67806 ,  0.44561 ,  0.65707 ,  0.1045  ,
        0.46217 ,  0.19912 ,  0.25802 ,  0.057194,  0.53443 , -0.43133 ,
       -0.34311 ,  0.59789 , -0.58417 ,  0.068995,  0.23944 , -0.85181 ,
        0.30379 , -0.34177 , -0.25746 , -0.031101, -0.16285 ,  0.45169 ,
       -0.91627 ,  0.64521 ,  0.73281 , -0.22752 , 

In [26]:
glove["queen"]

array([-0.50045 , -0.70826 ,  0.55388 ,  0.673   ,  0.22486 ,  0.60281 ,
       -0.26194 ,  0.73872 , -0.65383 , -0.21606 , -0.33806 ,  0.24498 ,
       -0.51497 ,  0.8568  , -0.37199 , -0.58824 ,  0.30637 , -0.30668 ,
       -0.2187  ,  0.78369 , -0.61944 , -0.54925 ,  0.43067 , -0.027348,
        0.97574 ,  0.46169 ,  0.11486 , -0.99842 ,  1.0661  , -0.20819 ,
        0.53158 ,  0.40922 ,  1.0406  ,  0.24943 ,  0.18709 ,  0.41528 ,
       -0.95408 ,  0.36822 , -0.37948 , -0.6802  , -0.14578 , -0.20113 ,
        0.17113 , -0.55705 ,  0.7191  ,  0.070014, -0.23637 ,  0.49534 ,
        1.1576  , -0.05078 ,  0.25731 , -0.091052,  1.2663  ,  1.1047  ,
       -0.51584 , -2.0033  , -0.64821 ,  0.16417 ,  0.32935 ,  0.048484,
        0.18997 ,  0.66116 ,  0.080882,  0.3364  ,  0.22758 ,  0.1462  ,
       -0.51005 ,  0.63777 ,  0.47299 , -0.3282  ,  0.083899, -0.78547 ,
        0.099148,  0.039176,  0.27893 ,  0.11747 ,  0.57862 ,  0.043639,
       -0.15965 , -0.35304 , -0.048965, -0.32461 , 

In [29]:
print(glove.most_similar(positive=["king", "woman"], negative=["man"], topn=3))
print(glove.most_similar(positive=["paris", "italy"], negative=["france"], topn=3))

# Es la misma cuenta pero hecha a mano
v = glove["king"] - glove["man"] + glove["woman"]
print(glove.similar_by_vector(v, topn=5))

[('queen', 0.7698540687561035), ('monarch', 0.6843381524085999), ('throne', 0.6755736470222473)]
[('rome', 0.8189547061920166), ('milan', 0.7376196980476379), ('naples', 0.7117615342140198)]
[('king', 0.8551837205886841), ('queen', 0.783441424369812), ('monarch', 0.6933802366256714), ('throne', 0.6833109855651855), ('daughter', 0.6809081435203552)]


## Embeddings pre-entrenados (español)
FastText entrenado sobre Common Crawl y Wikipedia, 300 dimensiones. Se debe descargar desde:
`https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.es.300.vec.gz`

Cargamos solo las 200.000 palabras más frecuentes para que entre en memoria.

In [30]:
from gensim.models import KeyedVectors

es = KeyedVectors.load_word2vec_format("../bin/cc.es.300.vec.gz", limit=200_000)
print(es.most_similar("rey", topn=5))
print(es.most_similar(positive=["rey", "mujer"], negative=["hombre"], topn=5))
print(es.most_similar(positive=["París", "Italia"], negative=["Francia"], topn=5))

[('monarca', 0.7845166325569153), ('Rey', 0.7571032643318176), ('príncipe', 0.7237560153007507), ('reyes', 0.6553534269332886), ('emperador', 0.6547355651855469)]
[('reina', 0.6996200084686279), ('princesa', 0.6584171056747437), ('monarca', 0.5745182633399963), ('emperatriz', 0.5571600794792175), ('Rey', 0.5523390173912048)]
[('Milán', 0.8195798397064209), ('Turín', 0.7262915968894958), ('Roma', 0.7253644466400146), ('Nápoles', 0.6508110761642456), ('Bérgamo', 0.63908451795578)]


In [31]:
pares_en = [("king", "queen"), ("car", "banana"), ("doctor", "nurse")]
pares_es = [("rey", "reina"), ("coche", "plátano"), ("médico", "enfermera")]

for (a, b), (c, d) in zip(pares_en, pares_es):
    print(f"{a}-{b}: {glove.similarity(a, b):.2f}   |   {c}-{d}: {es.similarity(c, d):.2f}")

king-queen: 0.75   |   rey-reina: 0.61
car-banana: 0.15   |   coche-plátano: 0.18
doctor-nurse: 0.75   |   médico-enfermera: 0.61


## Sesgos

In [32]:
print(glove.most_similar(positive=["doctor", "woman"], negative=["man"], topn=5))
print(glove.most_similar(positive=["programmer", "woman"], negative=["man"], topn=5))

[('nurse', 0.7735227942466736), ('physician', 0.7189430594444275), ('doctors', 0.6824328303337097), ('patient', 0.6750683188438416), ('dentist', 0.6726033091545105)]
[('educator', 0.5853328704833984), ('programmers', 0.5730530023574829), ('linguist', 0.5432007312774658), ('technician', 0.5373360514640808), ('freelance', 0.5362123250961304)]


## Transformers

In [21]:
import numpy as np

def coseno(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))


In [33]:
import torch
from transformers import AutoTokenizer, AutoModel

nombre = "bert-base-multilingual-cased"
tokenizador = AutoTokenizer.from_pretrained(nombre)
bert = AutoModel.from_pretrained(nombre).eval()

def vector(oracion, palabra):
    enc = tokenizador(oracion, return_tensors="pt")
    ids = enc["input_ids"][0].tolist()
    pid = tokenizador.convert_tokens_to_ids(palabra)
    assert pid != tokenizador.unk_token_id and pid in ids, f"'{palabra}' no es un único token"
    with torch.no_grad():
        h = bert(**enc).last_hidden_state[0]
    return h[ids.index(pid)].numpy()

plaza   = vector("Me senté en el banco de la plaza.", "banco")
dinero1 = vector("Fui al banco a sacar dinero.", "banco")
dinero2 = vector("El banco aprobó mi préstamo.", "banco")

print("plaza  vs dinero1:", round(float(coseno(plaza, dinero1)), 3))
print("dinero1 vs dinero2:", round(float(coseno(dinero1, dinero2)), 3))

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4892.45it/s]
[transformers] BertModel LOAD REPORT from: bert-base-multilingual-cased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


plaza  vs dinero1: 0.623
dinero1 vs dinero2: 0.747


In [37]:
p1   = vector("La película estuvo buena.", "película")
p2 = vector("La película fue un desastre.", "película")

p1

array([-2.35414729e-01, -1.25177443e+00,  4.58548844e-01,  1.39241830e-01,
        5.54735541e-01,  3.33907306e-01,  1.66972041e-01, -8.18277001e-01,
        5.09756505e-01,  2.19535068e-01,  3.06349456e-01,  4.01563913e-01,
        4.66584861e-02,  5.59342027e-01, -1.64091736e-01, -6.36056900e-01,
        2.67835051e-01,  1.53640318e+00, -2.41724141e-02, -2.33924299e-01,
       -3.70578974e-01,  1.96562763e-02, -6.46499515e-01,  1.88735247e-01,
       -2.07204092e-03,  4.97102678e-01, -5.75149596e-01,  3.93436611e-01,
        3.13873082e-01,  2.69701034e-01, -4.23937052e-01, -1.47064373e-01,
       -5.47970533e-01, -2.66378462e-01,  4.60714400e-01, -1.39769942e-01,
       -6.10441938e-02,  2.37532571e-01,  1.13166131e-01,  1.90683212e-02,
       -8.15184653e-01, -6.00975871e-01,  1.22380946e-02, -3.52519825e-02,
       -2.16647848e-01,  6.31795585e-01, -1.53420806e-01, -5.05536675e-01,
        7.98557520e-01,  2.33917236e-01,  2.59392381e-01, -4.93026525e-02,
       -2.97237843e-01, -

In [38]:
p2

array([ 1.02640465e-02, -9.29054976e-01,  5.56256831e-01,  4.83907968e-01,
        2.40865976e-01,  1.00384012e-01,  2.11566180e-01, -1.70542479e-01,
        3.50740969e-01,  4.89410490e-01,  6.16684973e-01,  3.65697980e-01,
        1.57188863e-01,  3.18216532e-01,  4.15247679e-03, -1.50550649e-01,
        3.22515249e-01,  6.03399634e-01, -4.75759385e-03, -5.39703146e-02,
       -1.93644360e-01, -6.46927953e-02, -3.63094896e-01,  2.90532317e-02,
       -3.22417498e-01,  7.12532401e-01, -2.91751236e-01,  3.59111637e-01,
        7.50172362e-02,  1.01263292e-01, -4.90735918e-01,  2.58989096e-01,
       -1.88228786e-01,  6.48491010e-02,  1.94462195e-01,  2.46108234e-01,
       -3.80212754e-01,  6.61412552e-02,  2.80905187e-01, -1.13226801e-01,
       -4.93261367e-01, -3.32659408e-02,  1.32033071e-02,  2.50205040e-01,
       -1.93781406e-01,  3.12711358e-01, -3.05205911e-01,  3.33396136e-03,
        4.65390295e-01, -5.83379149e-01,  6.67416975e-02, -1.12892613e-01,
       -4.16109234e-01, -